import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { Card } from "@components/home/Card";
import { Grid, Heading } from "@chakra-ui/react";
import styled from "@emotion/styled";
import { useRouter } from "next/router";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const router = useRouter();

  const handleClickCard = (value: string) => {
    router.push(value);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container>
          <div className="title">
            <Heading>간편 정보</Heading>
          </div>
          <Grid templateColumns="repeat(3, 1fr)" gap={6}>
            <Card
              content="달력"
              src="./images/calendar.png"
              onClick={() => handleClickCard("/calendar")}
            />
            <Card
              content="날짜계산기"
              src="./images/calculator.png"
              onClick={() => handleClickCard("/")}
            />
          </Grid>
        </Container>
      </main>
    </>
  );
}

const Container = styled.div`
  width: 100%;
  height: 100%;

  .title {
    display: flex;
    justify-content: center;
    padding-bottom: 50px;
  }
`;
