name: Deploy to Github Pages

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        uses: actions/setup-node@v3
        with:
          node-version: 19.x

      - run: npm install

      - name: Build
      - run: echo "remove rotots.txt & sitemap.xml"
      - run: rimraf public/robots.txt public/sitemap*.xml

      - run: npm run build
      - run: |
          echo "export : make /out directory"    
          npm run export
        env:
          CI: true
          DEPLOY_TARGET: gh-pages

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: out
          CLEAN: true
