name: Deploy to Github Pages

on:
  push:
    branches: "main"
  pull_request:
    branches: "main"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install Dependencies
        uses: actions/setup-node@v3
        with:
          node-version: 19.x
      - run: npm install

      - name: Build
        run: |
          echo "remove rotots.txt & sitemap.xml"
          rm -rf public/robots.txt public/sitemap*.xml
      - run: npm run build
      - run: |
          echo "export : make /out directory"    
          npm run export
        env:
          CI: true
          DEPLOY_TARGET: gh-pages

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          BRANCH: gh-pages
          FOLDER: out
          CLEAN: true
