name: Crawling CI

on:
  schedule:
    - cron: "0 0 * * 1,3,5"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      deployments: read
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Install Dependencies Using Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci

      - name: Crawling & Update
        run: npm run crawler

      - name: Create local changes
        run: |
          git add src/data/
      - name: Commit files
        run: |
          git config --local user.email "jjlee1623@gmail.com"
          git config --local user.name "JeongjooLee"
          git commit -a -m "cron : Update crawling data"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN }}
          branch: main
